package org.yassineabou.llms.app.core.data.local

/**
 * These data classes were originally auto-generated by SQLDelight.
 * They are now maintained manually so that the entire Compose UI layer
 * (ViewModels, screens, AsyncManager, RemoteDataSource) continues to
 * compile and behave identically after the migration to SQLiteNow.
 *
 * IMPORTANT: Do NOT delete these. The mapping layer in DatabaseMappers.kt
 * converts SQLiteNow query results into these classes.
 */

public data class Chats(
    public val id: String,
    public val title: String,
    public val description: String?,
    public val text_model_name: String,
    public val is_bookmarked: Long,
    public val created_at: String,
)

public data class Chat_messages(
    public val id: Long,
    public val chat_id: String,
    public val message: String,
    public val is_user: Long,
    public val timestamp: String?,
)

public data class Generated_images(
    public val id: String,
    public val prompt: String,
    public val image_data: ByteArray,
    public val image_model_name: String,
    public val generated_at: String?,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as Generated_images

        if (id != other.id) return false
        if (prompt != other.prompt) return false
        if (!image_data.contentEquals(other.image_data)) return false
        if (image_model_name != other.image_model_name) return false
        if (generated_at != other.generated_at) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + prompt.hashCode()
        result = 31 * result + image_data.contentHashCode()
        result = 31 * result + image_model_name.hashCode()
        result = 31 * result + (generated_at?.hashCode() ?: 0)
        return result
    }
}

public data class User(
    public val id: Long,
    public val google_sub_id: String,
    public val email: String,
    public val username: String,
    public val profile_pic_url: String?,
    public val created_at: String,
)